# executive_direction_pipeline/serializers.py
from rest_framework import serializers
from .models import Unit, MinutesOfMeeting, TaskAssignment

class UnitSerializer(serializers.ModelSerializer):
    class Meta:
        model = Unit
        fields = ['id', 'name', 'abbreviation', 'description'] # Fields to include in JSON

class TaskAssignmentSerializer(serializers.ModelSerializer):
    # Make assigned_units read-only in list view, populated by the view logic
    # Or provide a nested serializer if you need more detail automatically
    assigned_units = UnitSerializer(many=True, read_only=True)

    class Meta:
        model = TaskAssignment
        fields = ['id', 'mom', 'description', 'assigned_units', 'verbatim_sentence', 'created_at']
        read_only_fields = ['mom', 'created_at'] # Usually set by the backend

class MinutesOfMeetingSerializer(serializers.ModelSerializer):
    # tasks = TaskAssignmentSerializer(many=True, read_only=True) # Optional: include related tasks

    class Meta:
        model = MinutesOfMeeting
        fields = ['id', 'title', 'text', 'summary', 'meeting_date', 'created_at', 'original_audio_filename', 'original_pdf_filename'] # Add 'tasks' if uncommented above
        read_only_fields = ['summary', 'created_at'] # Summary is generated by backend